### ISSUE TITLE
How to handle LimeSurvey 3 LTS

### ISSUE THREAD

**Issue by martialblog** [martialblog/helm-charts#29]
Besides some Variables I don't think we need to change much for the LimeSurvey 3 LTS

These are not required:
```
  encrypt:
    keypair: ""
    publicKey: ""
    secretKey: ""
    nonce: ""
    secretBoxKey: ""
```

Anything else? :thinking:
