### ISSUE TITLE
If the Ingress is enabled the Base/Public URLs need to be the Ingress' host

### ISSUE THREAD

**Issue by martialblog** [martialblog/helm-charts#40]
For example if you set

```
ingress:
  enabled: true
  hosts:
    - host: limesurvey.local
      paths:
        - path: /
          pathType: Prefix
```

then the `baseUrl` und `publicURL` need to be `limesurvey.local`. Maybe we can provide some logic to do that in the template, so that it works out-of-the-box

```
- name: BASE_URL
  value: {{ .Values.limesurvey.baseUrl }}
- name: PUBLIC_URL
  value: {{ .Values.limesurvey.publicUrl }}
```
