### ISSUE TITLE
Liveness and readiness probes not configurable

### ISSUE THREAD

**Issue by Bloodiko** [martialblog/helm-charts#84]
In our case, the default Timeout for liveness and readiness are 1s, 

This sometimes set the Ready state to 0/1 as the pod was too slow to answer in a few cases. 
Basically forcing the pod to restart. 

Adjusting the Probe timeouts within the values chart may be helpful.

```
livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
```

we just hardcoded the timout manually in the deployment.yaml currently, but adjusting it within the values yaml should help.
