### ISSUE TITLE
ejabberd Helm chart missing from index.yaml

### ISSUE THREAD

**Issue by jacksgt** [martialblog/helm-charts#87]
Hi,

I noticed that the reference to the ejabberd chart has vanished from the index.yaml - I believe it used to be there.

https://martialblog.github.io/helm-charts/index.yaml

The last CI jobs also mentions the chart, so I'm not sure which puzzle piece is missing:

```
Looking up latest tag...
Discovering changed charts since 'ejabberd-0.1.0'...
WARNING: .github/Chart.yaml is missing, assuming that '.github' is not a Helm chart. Skipping.
Nothing to do. No chart changes detected.
```

https://github.com/martialblog/helm-charts/actions/runs/6081404816/job/16496989259

**Comment by martialblog** [comment]
Sorry, haven't had time to investigate, maybe I'll get to it next week.

**Comment by jacksgt** [comment]
Fixed with latest release: https://github.com/martialblog/helm-charts/releases/tag/ejabberd-0.3.1

```
curl https://martialblog.github.io/helm-charts/index.yaml

apiVersion: v1
entries:
  ejabberd:
  - apiVersion: v2
    created: "2025-10-06T14:27:14.237818084Z"
    description: A Helm chart for installing the ejabberd messaging server on Kubernetes
    digest: aa1000372ca0ef4bc64aacce6d051ac415716722b52555d110a477d46d095a51
    icon: https://raw.githubusercontent.com/processone/docs.ejabberd.im/master/content/assets/img/footer_logo_e.png
    keywords:
    - ejabberd
    - messaging
    - xmpp
    - mqtt
    - stun
    - turn
    - sip
    - matrix
    name: ejabberd
    sources:
    - https://github.com/processone/ejabberd
    type: application
    urls:
    - https://github.com/martialblog/helm-charts/releases/download/ejabberd-0.3.1/ejabberd-0.3.1.tgz
    version: 0.3.1
...
```
